---
name: miusu
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter_sdk: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  get_it: ^6.1.1
  google_fonts: ^2.0.0
  http: ^0.13.1
  wiredash: ^0.6.2
  youtube_player_flutter: ^8.0.0
  hive: ^2.0.4
  path_provider: ^2.0.1
  flare_flutter: ^3.0.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.0.2
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/svgs/
  - assets/pngs/
  - assets/languages/
  - assets/animations/
